### ISSUE TITLE
Implement spam filter

### ISSUE THREAD

**Issue by AndreaIdini** [Pandry/go-scienzabot#8]
Implementare uno o più dei seguenti tipi di spam filter (ordine di priorità, valuta cosa viene più facile):

- Piccolo Captcha (`Benvenuto nel gruppo scienza, scrivi "ciao gruppo scienza" e una breve presentazione nei prossimi 5 minuti per evitare il kick e rimanere nel gruppo`) e/o obbligo di presentazione 
- Vietare di default inoltro e messaggi con link, foto o gif a chi entra. Sblocco dopo 100 messaggi o qualche tempo.
- Blacklist (autokick/ban a chiunque abbia "bot" nel nome)

**Comment by Pandry** [comment]
Il captcha potrebbe essere implementato chiedendo all'utente di "tappare" un pulsante nella tastiera inline.

Per quanto riguarda i messaggi con link, credo sia possibile gestire la cosa con un sistema di permessi di telegram

Per quanto riguarda la blacklist, magari idealmente potrei mettere una lista di espressioni RegEX.
Idealmente altrimenti, ci si potrebbe limitare a rimuovere il permesso di scrivere nel gruppo al presunto utente

**Comment by Pandry** [comment]
Temporary solution made
Basically, the user needs to click a button to verify itself.
